---
title: "XGBoost"
author: "Anushka Kapoor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xgboostExplainer)
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(caret)
library(xgboost)
```

```{r}
load("~/Desktop/MSBA Class'24/Machinelearning/MachineLearning/returns_sp500.RData")
ticker <- "AAPL"
total_data <- returns_sp500 %>% filter(Ticker == ticker, Date >= "2022-06-24") %>% select(Date, Open, High, Low, Movement, Close)
total_data$Movement <- as.numeric(total_data$Movement == "Up")

```

```{r}
set.seed(7)
total_obs <- nrow(total_data)
train_data_indices <- sample(1:total_obs, floor(0.8 * total_obs))
train_data <- total_data[train_data_indices, ]
test_data <- total_data[-train_data_indices, ]
```

```{r}
# Convert the data to DMatrix format for XGBoost
dtrain <- xgb.DMatrix(data = as.matrix(train_data[, -c(1, 6)]), label = train_data$Close)
dtest <- xgb.DMatrix(data = as.matrix(test_data[, -c(1, 6)]), label = test_data$Close)
```

```{r}
# Train the XGBoost model
#xg_model <- xgb.train(params = params, data = dtrain, nrounds = 100)

set.seed(111111)
bst_1 <- xgboost(data = dtrain, # Set training data
               objective = "reg:squarederror",
                eval_metric = "rmse",
                eval_metric = "error",
                max_depth = 3,
                verbose = 1, 
                print_every_n = 20,
                eta = 0.1,
                nrounds = 100)

```
```{r}
# Make predictions on the test data
predictions <- predict(bst_1, dtest)
```

```{r}
# Calculate the accuracy of the model
accuracy <- sqrt(mean((test_data$Close - predictions)^2))
```

```{r}
# Plot actual vs predicted test data
ggplot() +
  geom_line(aes(x = test_data$Date, y = test_data$Close, color = "Actual"), size = 1.2) +
  geom_line(aes(x = test_data$Date, y = predictions, color = "Predicted"), size = 1.2) +
  labs(title = "Actual vs Predicted Test Data", x = "Date", y = "Close Price") +
  scale_color_manual(values = c("Actual" = "blue", "Predicted" = "red"))
```


```{r}
xg_model <- train(
  x = as.matrix(train_data[, -c(1, 6)]),
  y = train_data$Close,
  method = "xgbTree",
  objective="reg:squarederror",
  trControl = trainControl(method="repeatedcv",
                           number=3,
                           repeats=2,
                           verboseIter = TRUE),
  tuneGrid = expand.grid(nrounds=c(50, 100, 150),
                         eta = c(0.01, 0.1, 0.3),
                         max_depth = c(3, 6, 9),
                         colsample_bytree=c(0.5,1),
                         subsample=c(0.5,1),
                         gamma=c(0,50),
                         min_child_weight=c(0,20)))
```

```{r}
#Aggregating results
# Selecting tuning parameters
# Fitting nrounds = 150, max_depth = 6, eta = 0.1, gamma = 0, colsample_bytree = 1, min_child_weight = 0, subsample = 0.5 on full training set
```

```{r}
bst_best <- xgboost(data = dtrain, # Set training data
               objective = "reg:squarederror",
                eval_metric = "rmse",
                eval_metric = "error",
                max_depth = 6,
                verbose = 1, 
                print_every_n = 20,
                eta = 0.1,
                nrounds = 150,
                colsample_bytree=1,
                subsample=0.5,
                gamma=0,
                min_child_weight=0)

```


```{r}
predictions <- predict(bst_best, dtest)
rmse <- sqrt(mean((test_data$Close - predictions)^2))
mae <- mean(abs(predictions - test_data$Close))
mse <- mean((predictions - test_data$Close)^2)
rmse
mae
mse
```

```{r}
plot_data <- data.frame(
  Date = test_data$Date,
  Actual = test_data$Close,
  Predicted = predictions
)

ggplot(plot_data, aes(x = Date)) +
  geom_line(aes(y = Actual, color = "Actual"), size = 1.2) +
  geom_line(aes(y = Predicted, color = "Predicted"), size = 1.2) +
  labs(title = "Actual vs Predicted Test Data", x = "Date", y = "Close Price") +
  scale_color_manual(values = c("Actual" = "blue", "Predicted" = "red"))+
  theme_minimal()

```

